name: Release
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Building the Images
        run: docker build . -t dilipsingh27/k8s-backend
      - name: Logging into the DockerHub 
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Pushing the images to dockerhub repository
        run: docker push dilipsingh27/k8s-backend